version: "2"

services:
  postgres:
    image: "postgres:9-alpine"
    volumes:
      - ${HOME}/demoAppData:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=reed
      - POSTGRES_PASSWORD=reed
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
